version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/client"
      schedule:
          interval: "weekly"
      allow:
          - dependency-type: direct
      open-pull-requests-limit: 3
